[package]
name = "weather"
version = "0.1.0"
authors = []
edition = "2018"

[profile.release]
debug = true

[dependencies]
fastly = "^0.8.0"
serde_json = "1.0.57"
tinytemplate = "1.1"
serde = { version = "1.0", features = ["derive"] }
chrono = "0.4.15"
weather_helpers = "0.1.2"
